use rand::Rng;
use rayon::prelude::*;
use regex::Regex;
use reqwest::blocking::Client;
use reqwest::StatusCode;
use std::collections::HashSet;
use std::fs;
use std::io::Write;
use std::net::IpAddr;
use std::net::{TcpStream, ToSocketAddrs, UdpSocket};
use std::path::{Path, PathBuf};
use std::sync::mpsc;
use std::sync::OnceLock;
use std::thread;
use std::time::{SystemTime, UNIX_EPOCH};
use std::time::Duration;
use url::Url;

const DEFAULT_TIMEOUT_SECS: u64 = 10;
const DEFAULT_WORKERS: usize = 20;

#[derive(Debug, Clone, PartialEq, Eq)]
enum Status {
    Alive,
    Dead,
    Invalid,
}

#[derive(Debug, Clone)]
struct CheckResult {
    url: String,
    status: Status,
}

fn parse_tracker_line(line: &str) -> String {
    let trimmed = line.trim();
    if trimmed.starts_with('[') && trimmed.contains("](") && trimmed.ends_with(')') {
        if let Some((_, right)) = trimmed.split_once("](") {
            return right.trim_end_matches(')').to_string();
        }
    }
    trimmed.to_string()
}

fn tracker_regex() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"(?i)(https?|udp|wss)://[^\s,]*?/announce")
        .expect("invalid tracker regex"))
}

fn collapse_path_slashes(path: &str) -> String {
    let mut out = String::with_capacity(path.len());
    let mut prev_slash = false;

    for ch in path.chars() {
        if ch == '/' {
            if !prev_slash {
                out.push(ch);
            }
            prev_slash = true;
        } else {
            out.push(ch);
            prev_slash = false;
        }
    }

    if out.is_empty() {
        "/".to_string()
    } else {
        out
    }
}

fn normalize_tracker_url(raw: &str) -> Option<String> {
    let candidate = raw
        .trim()
        .trim_matches(|c: char| "\"'<>[](){};,.".contains(c));

    let mut url = Url::parse(candidate).ok()?;
    let scheme = url.scheme().to_lowercase();

    if !matches!(scheme.as_str(), "http" | "https" | "udp" | "wss") {
        return None;
    }

    let host = url.host_str()?;
    let host_is_ip = host.parse::<IpAddr>().is_ok();
    if !host_is_ip && !host.contains('.') {
        return None;
    }

    let normalized_path = collapse_path_slashes(url.path());
    if !normalized_path.ends_with("/announce") {
        return None;
    }
    url.set_path(&normalized_path);
    url.set_query(None);
    url.set_fragment(None);

    let port = url.port();
    let should_drop_default_port = (scheme == "http" && port == Some(80))
        || (scheme == "https" && port == Some(443));

    if should_drop_default_port {
        let _ = url.set_port(None);
    }

    Some(url.to_string())
}

fn bdecode_simple(data: &[u8]) -> bool {
    if data.is_empty() || data[0] != b'd' {
        return false;
    }

    data.windows(b"interval".len()).any(|w| w == b"interval")
        || data.windows(b"peers".len()).any(|w| w == b"peers")
        || data
            .windows(b"failure reason".len())
            .any(|w| w == b"failure reason")
}

fn is_parked_or_expired_domain(content: &[u8]) -> bool {
    let content_lower = String::from_utf8_lossy(content).to_lowercase();
    let indicators = [
        "domain for sale",
        "domain is for sale",
        "buy this domain",
        "domain expired",
        "domain has expired",
        "this domain is expired",
        "register this domain",
        "domain available",
        "parked domain",
        "domain parking",
        "coming soon",
        "under construction",
        "page not found",
        "404 not found",
        "namecheap",
        "godaddy parked",
        "sedo domain parking",
        "domain portfolio",
        "premium domain",
        "afternic",
        "escrow.com",
        "dan.com/buy-domain",
        "undeveloped",
        "this webpage was generated by the domain owner",
        "hugedomains.com",
        "bodis.com",
        "sedoparking",
    ];

    if indicators.iter().any(|word| content_lower.contains(word)) {
        return true;
    }

    let head = String::from_utf8_lossy(&content[..content.len().min(500)]).to_lowercase();
    head.contains("<html") || head.contains("<!doctype html")
}

fn check_http_tracker(url: &str, timeout: Duration) -> Status {
    let client = match Client::builder().timeout(timeout).build() {
        Ok(c) => c,
        Err(_) => return Status::Dead,
    };

    let mut rng = rand::thread_rng();
    let peer_id_random: String = (0..12)
        .map(|_| (rng.gen_range(0u8..=9) + b'0') as char)
        .collect();
    let peer_id = format!("-RS0001-{peer_id_random}");

    let response = match client
        .get(url)
        .query(&[
            ("info_hash", "00000000000000000000"),
            ("peer_id", peer_id.as_str()),
            ("port", "6881"),
            ("uploaded", "0"),
            ("downloaded", "0"),
            ("left", "0"),
            ("compact", "1"),
            ("event", "started"),
        ])
        .send()
    {
        Ok(r) => r,
        Err(_) => return Status::Dead,
    };

    let status_code = response.status();
    let body = response.bytes().unwrap_or_default().to_vec();

    if is_parked_or_expired_domain(&body) {
        return Status::Invalid;
    }

    if bdecode_simple(&body) {
        return Status::Alive;
    }

    if status_code == StatusCode::OK {
        let head = String::from_utf8_lossy(&body[..body.len().min(200)]).to_lowercase();
        if head.contains("<html") || head.contains("<body") || head.contains("<head") {
            return Status::Invalid;
        }
        if body.len() > 50_000 {
            return Status::Invalid;
        }
        return Status::Dead;
    }

    if status_code == StatusCode::BAD_REQUEST || status_code == StatusCode::FORBIDDEN {
        if bdecode_simple(&body) {
            return Status::Alive;
        }
    }

    Status::Dead
}

fn check_udp_tracker(url: &str, timeout: Duration) -> Status {
    let parsed = match Url::parse(url) {
        Ok(p) => p,
        Err(_) => return Status::Invalid,
    };

    let host = match parsed.host_str() {
        Some(h) => h,
        None => return Status::Invalid,
    };
    let port = parsed.port().unwrap_or(80);

    let addr = match format!("{host}:{port}")
        .to_socket_addrs()
        .ok()
        .and_then(|mut it| it.next())
    {
        Some(a) => a,
        None => return Status::Invalid,
    };

    let socket = match UdpSocket::bind("0.0.0.0:0") {
        Ok(s) => s,
        Err(_) => return Status::Dead,
    };

    let _ = socket.set_read_timeout(Some(timeout));
    let _ = socket.set_write_timeout(Some(timeout));

    let connection_id: u64 = 0x41727101980;
    let action: u32 = 0;
    let transaction_id: u32 = rand::thread_rng().r#gen();

    let mut req = Vec::with_capacity(16);
    req.extend_from_slice(&connection_id.to_be_bytes());
    req.extend_from_slice(&action.to_be_bytes());
    req.extend_from_slice(&transaction_id.to_be_bytes());

    if socket.send_to(&req, addr).is_err() {
        return Status::Dead;
    }

    let mut response = [0u8; 16];
    match socket.recv_from(&mut response) {
        Ok((size, _)) if size >= 8 => Status::Alive,
        Ok(_) => Status::Alive,
        Err(_) => Status::Dead,
    }
}

fn check_wss_tracker(url: &str, timeout: Duration) -> Status {
    let parsed = match Url::parse(url) {
        Ok(p) => p,
        Err(_) => return Status::Invalid,
    };

    let host = match parsed.host_str() {
        Some(h) => h,
        None => return Status::Invalid,
    };
    let port = parsed.port().unwrap_or(443);

    let addr = match format!("{host}:{port}")
        .to_socket_addrs()
        .ok()
        .and_then(|mut it| it.next())
    {
        Some(a) => a,
        None => return Status::Invalid,
    };

    match TcpStream::connect_timeout(&addr, timeout) {
        Ok(_) => Status::Alive,
        Err(_) => Status::Dead,
    }
}

fn validate_tracker(tracker: &str, timeout: Duration) -> CheckResult {
    let parsed = match Url::parse(tracker) {
        Ok(p) => p,
        Err(_) => {
            return CheckResult {
                url: tracker.to_string(),
                status: Status::Invalid,
            }
        }
    };

    let protocol = parsed.scheme().to_lowercase();
    let status = match protocol.as_str() {
        "http" | "https" => check_http_tracker(tracker, timeout),
        "udp" => check_udp_tracker(tracker, timeout),
        "wss" => check_wss_tracker(tracker, timeout),
        _ => Status::Invalid,
    };

    CheckResult {
        url: tracker.to_string(),
        status,
    }
}

fn dedupe_keep_order(items: Vec<String>) -> Vec<String> {
    let mut seen = HashSet::new();
    let mut out = Vec::new();
    for item in items {
        if seen.insert(item.clone()) {
            out.push(item);
        }
    }
    out
}

fn sort_and_dedupe(mut items: Vec<String>) -> Vec<String> {
    items.sort_unstable();
    items.dedup();
    items
}

fn load_trackers(input_file: &str) -> Result<Vec<String>, String> {
    let text = fs::read_to_string(input_file)
        .map_err(|_| format!("Error: {input_file} not found or unreadable"))?;

    let normalized_text = text.replace(',', "\n");

    let mut trackers = Vec::new();
    for line in normalized_text.lines() {
        let parsed = parse_tracker_line(line);
        if parsed.is_empty() || parsed.starts_with('#') {
            continue;
        }

        for matched in tracker_regex().find_iter(&parsed) {
            if let Some(normalized) = normalize_tracker_url(matched.as_str()) {
                trackers.push(normalized);
            }
        }
    }

    Ok(dedupe_keep_order(trackers))
}

fn filter_blacklist(trackers: Vec<String>, blacklist_file: &str) -> Vec<String> {
    if !Path::new(blacklist_file).exists() {
        return trackers;
    }

    let text = match fs::read_to_string(blacklist_file) {
        Ok(t) => t,
        Err(_) => return trackers,
    };

    let patterns = text
        .lines()
        .map(|line| line.trim())
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| line.to_string())
        .collect::<Vec<_>>();

    if patterns.is_empty() {
        return trackers;
    }

    trackers
        .into_iter()
        .filter(|tracker| !patterns.iter().any(|p| tracker.contains(p)))
        .collect()
}

fn write_lines(path: PathBuf, lines: &[String]) -> Result<(), String> {
    let mut file = fs::File::create(&path)
        .map_err(|e| format!("Failed to create {}: {}", path.display(), e))?;
    for line in lines {
        file.write_all(line.as_bytes())
            .and_then(|_| file.write_all(b"\n"))
            .map_err(|e| format!("Failed to write {}: {}", path.display(), e))?;
    }
    Ok(())
}

fn write_best_file(alive_items: &[CheckResult], output_file: &str) -> Result<(), String> {
    let all_alive = sort_and_dedupe(alive_items.iter().map(|i| i.url.clone()).collect());
    write_lines(PathBuf::from(output_file), &all_alive)
}

fn split_best_file_by_protocol(output_file: &str) -> Result<(), String> {
    let output_path = PathBuf::from(output_file);
    let output_dir = output_path
        .parent()
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| PathBuf::from("."));

    let content = fs::read_to_string(&output_path)
        .map_err(|e| format!("Failed to read {}: {}", output_path.display(), e))?;

    let mut http = Vec::new();
    let mut https = Vec::new();
    let mut udp = Vec::new();
    let mut wss = Vec::new();

    for line in content.lines() {
        let tracker = line.trim();
        if tracker.is_empty() {
            continue;
        }

        if let Ok(parsed) = Url::parse(tracker) {
            match parsed.scheme() {
                "http" => http.push(tracker.to_string()),
                "https" => https.push(tracker.to_string()),
                "udp" => udp.push(tracker.to_string()),
                "wss" => wss.push(tracker.to_string()),
                _ => {}
            }
        }
    }

    let http = sort_and_dedupe(http);
    let https = sort_and_dedupe(https);
    let udp = sort_and_dedupe(udp);
    let wss = sort_and_dedupe(wss);

    write_lines(output_dir.join("trackers_best_http.txt"), &http)?;
    write_lines(output_dir.join("trackers_best_https.txt"), &https)?;
    write_lines(output_dir.join("trackers_best_udp.txt"), &udp)?;
    write_lines(output_dir.join("trackers_best_wss.txt"), &wss)?;

    Ok(())
}

fn html_escape(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn tracker_protocol(url: &str) -> &'static str {
    if let Ok(parsed) = Url::parse(url) {
        match parsed.scheme() {
            "http" => "http",
            "https" => "https",
            "udp" => "udp",
            "wss" => "wss",
            _ => "other",
        }
    } else {
        "other"
    }
}

fn generate_github_pages(
    results: &[CheckResult],
    input_file: &str,
    output_file: &str,
) -> Result<(), String> {
    fs::create_dir_all("docs/public-stats")
        .map_err(|e| format!("Failed to create docs directory: {}", e))?;

    let total = results.len();
    let alive = results.iter().filter(|r| r.status == Status::Alive).count();
    let dead = results.iter().filter(|r| r.status == Status::Dead).count();
    let invalid = results.iter().filter(|r| r.status == Status::Invalid).count();

    let mut http_count = 0usize;
    let mut https_count = 0usize;
    let mut udp_count = 0usize;
    let mut wss_count = 0usize;

    for r in results {
        match tracker_protocol(&r.url) {
            "http" => http_count += 1,
            "https" => https_count += 1,
            "udp" => udp_count += 1,
            "wss" => wss_count += 1,
            _ => {}
        }
    }

    let uptime_pct = if total == 0 {
        0.0
    } else {
        (alive as f64) * 100.0 / (total as f64)
    };

    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    let alive_list = sort_and_dedupe(
        results
            .iter()
            .filter(|r| r.status == Status::Alive)
            .map(|r| r.url.clone())
            .collect(),
    );

    let mut ordered = results.to_vec();
    ordered.sort_by(|a, b| {
        let a_rank = match a.status {
            Status::Alive => 0,
            Status::Dead => 1,
            Status::Invalid => 2,
        };
        let b_rank = match b.status {
            Status::Alive => 0,
            Status::Dead => 1,
            Status::Invalid => 2,
        };
        a_rank.cmp(&b_rank).then_with(|| a.url.cmp(&b.url))
    });

    let rows = ordered
        .iter()
        .map(|r| {
            let status = match r.status {
                Status::Alive => "Online",
                Status::Dead => "Dead",
                Status::Invalid => "Invalid",
            };
            let status_class = match r.status {
                Status::Alive => "ok",
                Status::Dead => "bad",
                Status::Invalid => "warn",
            };
            format!(
                "<tr><td class=\"{status_class}\">{status}</td><td>{proto}</td><td><a href=\"{url}\" target=\"_blank\">{url}</a></td></tr>",
                proto = tracker_protocol(&r.url).to_uppercase(),
                url = html_escape(&r.url),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let index_html = format!(
        "<!doctype html>
<html lang=\"en\"> 
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>Tracker Status Dashboard</title>
  <style>
    body {{ font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial,sans-serif; margin:0; background:#0b1220; color:#e5e7eb; }}
    .wrap {{ max-width: 1200px; margin: 24px auto; padding: 0 16px; }}
    h1 {{ margin: 0 0 8px; }}
    .sub {{ color:#94a3b8; margin-bottom:16px; }}
        .actions {{ display:flex; gap:10px; flex-wrap:wrap; margin: 8px 0 16px; }}
        .btn {{ appearance:none; border:1px solid #334155; background:#0f172a; color:#e2e8f0; border-radius:8px; padding:8px 12px; cursor:pointer; text-decoration:none; font-size:14px; }}
        .btn:hover {{ background:#1e293b; }}
        .hint {{ color:#94a3b8; font-size:13px; margin-left:4px; }}
    .grid {{ display:grid; grid-template-columns: repeat(auto-fit,minmax(170px,1fr)); gap:12px; margin-bottom:16px; }}
    .card {{ background:#111827; border:1px solid #1f2937; border-radius:10px; padding:12px; }}
    .v {{ font-size:22px; font-weight:700; margin-top:4px; }}
    table {{ width:100%; border-collapse: collapse; background:#111827; border:1px solid #1f2937; }}
    th,td {{ border-bottom:1px solid #1f2937; padding:8px; text-align:left; }}
    th {{ background:#0f172a; }}
    a {{ color:#60a5fa; text-decoration:none; word-break: break-all; }}
    .ok {{ color:#22c55e; font-weight:600; }}
    .bad {{ color:#ef4444; font-weight:600; }}
    .warn {{ color:#f59e0b; font-weight:600; }}
    .foot {{ color:#64748b; margin-top:12px; font-size:12px; }}
  </style>
</head>
<body>
  <div class=\"wrap\">
    <h1>Live Tracker Status</h1>
        <div class=\"sub\">Generated by tracker-checker • input: {input} • output: {output}</div>
        <div class=\"actions\">
            <button id=\"copyBtn\" class=\"btn\" type=\"button\">Copy List</button>
            <a class=\"btn\" href=\"./trackers_best.txt\" download=\"trackers_best.txt\">Download TXT</a>
            <button id=\"refreshBtn\" class=\"btn\" type=\"button\">Refresh</button>
            <span id=\"hint\" class=\"hint\"></span>
        </div>
    <div class=\"grid\">
      <div class=\"card\">Global Uptime<div class=\"v\">{uptime:.2}%</div></div>
      <div class=\"card\">Total Checked<div class=\"v\">{total}</div></div>
      <div class=\"card\">Online<div class=\"v\">{alive}</div></div>
      <div class=\"card\">Dead<div class=\"v\">{dead}</div></div>
      <div class=\"card\">Invalid<div class=\"v\">{invalid}</div></div>
      <div class=\"card\">Protocols<div class=\"v\">H:{http} HS:{https} U:{udp} W:{wss}</div></div>
    </div>
    <table>
      <thead><tr><th>Status</th><th>Protocol</th><th>Tracker</th></tr></thead>
      <tbody>
        {rows}
      </tbody>
    </table>
    <div class=\"foot\">Generated timestamp (unix): {ts}</div>
  </div>
    <script>
        (() => {{
            const copyBtn = document.getElementById('copyBtn');
            const refreshBtn = document.getElementById('refreshBtn');
            const hint = document.getElementById('hint');

            function showHint(text) {{
                hint.textContent = text;
                setTimeout(() => {{
                    if (hint.textContent === text) hint.textContent = '';
                }}, 2200);
            }}

            async function loadListText() {{
                const resp = await fetch('./trackers_best.txt?ts={ts}', {{ cache: 'no-store' }});
                if (!resp.ok) throw new Error('Failed to load trackers_best.txt');
                const text = await resp.text();
                return text.trim();
            }}

            copyBtn.addEventListener('click', async () => {{
                try {{
                    const text = await loadListText();
                    if (!text) {{
                        showHint('List is empty');
                        return;
                    }}
                    await navigator.clipboard.writeText(text);
                    showHint('Copied');
                }} catch (_) {{
                    showHint('Copy failed');
                }}
            }});

            refreshBtn.addEventListener('click', () => {{
                location.reload();
            }});
        }})();
    </script>
</body>
</html>",
        input = html_escape(input_file),
        output = html_escape(output_file),
        uptime = uptime_pct,
        total = total,
        alive = alive,
        dead = dead,
        invalid = invalid,
        http = http_count,
        https = https_count,
        udp = udp_count,
        wss = wss_count,
        rows = rows,
        ts = ts
    );

    let public_stats_html = format!(
        "<!doctype html>
<html lang=\"en\"> 
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>Public Tracker Stats</title>
  <style>
    body {{ font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial,sans-serif; margin:0; background:#030712; color:#e5e7eb; }}
    .wrap {{ max-width:900px; margin:28px auto; padding: 0 16px; }}
    .k {{ display:grid; grid-template-columns: repeat(auto-fit,minmax(170px,1fr)); gap:12px; }}
    .c {{ background:#111827; border:1px solid #1f2937; border-radius:10px; padding:12px; }}
    .v {{ font-size:24px; font-weight:700; margin-top:4px; }}
    a {{ color:#60a5fa; }}
  </style>
</head>
<body>
  <div class=\"wrap\">
    <h1>🚀 Privacy Tracker - Public Stats</h1>
    <p>🔒 No IP logging • UDP preferred • static report by tracker-checker</p>
    <div class=\"k\">
      <div class=\"c\">TRACKERS CHECKED<div class=\"v\">{total}</div></div>
      <div class=\"c\">ONLINE<div class=\"v\">{alive}</div></div>
      <div class=\"c\">UPTIME<div class=\"v\">{uptime:.2}%</div></div>
      <div class=\"c\">UPDATED<div class=\"v\">{ts}</div></div>
    </div>
    <p style=\"margin-top:14px\"><a href=\"/tracker/\">Back to dashboard</a></p>
  </div>
</body>
</html>",
        total = total,
        alive = alive,
        uptime = uptime_pct,
        ts = ts
    );

    fs::write("docs/index.html", index_html)
        .map_err(|e| format!("Failed to write docs/index.html: {}", e))?;
    write_lines(PathBuf::from("docs/trackers_best.txt"), &alive_list)
        .map_err(|e| format!("Failed to write docs/trackers_best.txt: {}", e))?;
    fs::write("docs/public-stats/index.html", public_stats_html)
        .map_err(|e| format!("Failed to write docs/public-stats/index.html: {}", e))?;
    fs::write("docs/.nojekyll", "")
        .map_err(|e| format!("Failed to write docs/.nojekyll: {}", e))?;

    Ok(())
}

fn parse_args() -> Result<(String, String, usize), String> {
    let mut args = std::env::args().skip(1).collect::<Vec<_>>();
    if args.is_empty() {
        return Ok((
            "trackers.txt".to_string(),
            "trackers_best.txt".to_string(),
            DEFAULT_WORKERS,
        ));
    }

    let mut workers = DEFAULT_WORKERS;
    if let Some(pos) = args.iter().position(|a| a == "--workers") {
        if pos + 1 >= args.len() {
            return Err("--workers requires a value".to_string());
        }
        workers = args[pos + 1]
            .parse::<usize>()
            .map_err(|_| "Invalid --workers value".to_string())?;
        args.drain(pos..=pos + 1);
    }

    let input = args
        .first()
        .cloned()
        .unwrap_or_else(|| "trackers.txt".to_string());
    let output = args
        .get(1)
        .cloned()
        .unwrap_or_else(|| "trackers_best.txt".to_string());

    Ok((input, output, workers.max(1)))
}

fn status_tag(status: &Status) -> &'static str {
    match status {
        Status::Alive => "ALIVE",
        Status::Dead => "DEAD",
        Status::Invalid => "INVALID",
    }
}

fn main() {
    let (input_file, output_file, workers) = match parse_args() {
        Ok(v) => v,
        Err(e) => {
            eprintln!("❌ {e}");
            std::process::exit(1);
        }
    };

    println!("======================================================================");
    println!("TRACKER CHECKER - RUST STRICT MODE");
    println!("======================================================================");
    println!("Input file: {input_file}");
    println!("Output file: {output_file}");
    println!("Workers: {workers}");
    println!("======================================================================\n");

    let trackers = match load_trackers(&input_file) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("{e}");
            std::process::exit(1);
        }
    };

    let trackers = filter_blacklist(trackers, "blackstr.txt");
    let trackers = sort_and_dedupe(trackers);
    if trackers.is_empty() {
        eprintln!("Error: No trackers found in {input_file}");
        std::process::exit(1);
    }

    if let Err(e) = write_lines(PathBuf::from(&input_file), &trackers) {
        eprintln!("❌ {e}");
        std::process::exit(1);
    }

    println!("Checking {} trackers with STRICT validation...", trackers.len());

    let timeout = Duration::from_secs(DEFAULT_TIMEOUT_SECS);
    let total = trackers.len();
    let trackers_for_workers = trackers.clone();
    let (tx, rx) = mpsc::channel::<CheckResult>();

    let worker_handle = thread::spawn(move || {
        let pool = rayon::ThreadPoolBuilder::new()
            .num_threads(workers)
            .build()
            .expect("failed to create thread pool");

        pool.install(|| {
            trackers_for_workers
                .par_iter()
                .for_each_with(tx, |sender, tracker| {
                    let result = validate_tracker(tracker, timeout);
                    let _ = sender.send(result);
                });
        });
    });

    let mut all_results: Vec<CheckResult> = Vec::with_capacity(total);
    let mut alive: Vec<CheckResult> = Vec::new();
    let mut dead_count = 0usize;
    let mut invalid_count = 0usize;
    let mut completed = 0usize;

    for result in rx {
        completed += 1;
        println!(
            "[{}/{}] {} {}",
            completed,
            total,
            status_tag(&result.status),
            result.url
        );

        all_results.push(result.clone());

        match result.status {
            Status::Alive => alive.push(result),
            Status::Dead => dead_count += 1,
            Status::Invalid => invalid_count += 1,
        }
    }

    if worker_handle.join().is_err() {
        eprintln!("❌ checker worker thread panicked");
        std::process::exit(1);
    }

    println!("Generating trackers_best.txt...");
    if let Err(e) = write_best_file(&alive, &output_file) {
        eprintln!("❌ {e}");
        std::process::exit(1);
    }

    println!("Splitting trackers_best.txt by protocol...");
    if let Err(e) = split_best_file_by_protocol(&output_file) {
        eprintln!("❌ {e}");
        std::process::exit(1);
    }

    println!("Generating GitHub Pages static files...");
    if all_results.len() != total {
        eprintln!("❌ internal result count mismatch");
        std::process::exit(1);
    }

    if let Err(e) = generate_github_pages(&all_results, &input_file, &output_file) {
        eprintln!("❌ {e}");
        std::process::exit(1);
    }

    println!("\nDone! Results saved to {output_file}");
    println!("✓ Alive (Valid Trackers): {}", alive.len());
    println!("✗ Dead: {dead_count}");
    println!("⚠ Invalid (Parked/Expired/Not Trackers): {invalid_count}");
    println!("🌐 GitHub Pages files: docs/index.html, docs/public-stats/index.html");
}
